"""
Message ORM model — stores individual chat messages with optional embedding.
"""

import uuid
from datetime import datetime

from pgvector.sqlalchemy import Vector
from sqlalchemy import Boolean, DateTime, Enum, ForeignKey, Index, Integer, Text, func
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.core.config import settings
from app.core.db import Base


class Message(Base):
    __tablename__ = "messages"

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    session_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("chat_sessions.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )

    # DENORMALIZED FROM chat_sessions.user_id — DELIBERATELY, exactly as
    # chunks.user_id is (Phase 9). The messages arm filters on THIS column
    # rather than joining to chat_sessions, because pgvector's HNSW scan
    # applies the WHERE after walking its global candidate set: a tenant filter
    # on a joined table drops recall toward zero as the table grows. Written on
    # every insert from the owning session; NOT NULL is the tenant boundary.
    user_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), nullable=False)

    role: Mapped[str] = mapped_column(
        Enum("user", "assistant", "system", name="message_role"),
        nullable=False,
    )
    content: Mapped[str] = mapped_column(Text, nullable=False)
    token_count: Mapped[int | None] = mapped_column(Integer, nullable=True)

    # Match the configured embedding model so pgvector operations receive vectors
    # with the same dimension generated by the embedding service.
    embedding: Mapped[list[float]] = mapped_column(Vector(settings.EMBEDDING_DIMENSIONS), nullable=True)

    # True when the content exceeded the embedding model's token ceiling and was
    # embedded from a budgeted head instead of being silently truncated by the
    # encoder (invariant 6). The vector then represents only the head — a
    # queryable caveat on this row's retrievability, not a hidden one.
    embedding_truncated: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)

    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=func.now())

    __table_args__ = (
        # HNSW Index for ultra-fast vector similarity search (cosine distance)
        Index(
            "ix_messages_embedding_hnsw",
            "embedding",
            postgresql_using="hnsw",
            postgresql_with={"m": 16, "ef_construction": 64},
            postgresql_ops={"embedding": "vector_cosine_ops"},
        ),
        # The tenant filter column — indexed so the HNSW arm can pre-filter.
        Index("ix_messages_user_id", "user_id"),
    )

    # Relationships
    session = relationship("ChatSession", back_populates="messages")
